package com.example.demo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.sql.Timestamp;
import java.util.Date;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "health-check")
@DynamoDBDocument
public class Status {

    @DynamoDBHashKey(attributeName = "healthCheckID")
    @DynamoDBAutoGeneratedKey
    String healthCheckID;
    @DynamoDBAttribute(attributeName = "status")
    String eSIMhealthCheckStatus;
    @DynamoDBAttribute(attributeName = "timeStamp")
    String timeStamp;


    Status(String eSIMhealthCheckStatus){
        this.eSIMhealthCheckStatus = eSIMhealthCheckStatus;
        this.timeStamp = new Timestamp(System.currentTimeMillis()).toString();

    }
}
