package com.example.demo;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serializable;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "dev-users")
@DynamoDBDocument
@JsonAutoDetect
public class User implements Serializable {

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    private String userId;
    private String userName;
    private String email;
    private String phoneNumber;

}